# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPCMarketplace():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
        
    def test_homepage(self):
        self.driver.get("http://ec2-18-221-6-28.us-east-2.compute.amazonaws.com:8000/")
        time.sleep(3)
        
    def test_signUp(self):
        self.driver.get("http://ec2-18-221-6-28.us-east-2.compute.amazonaws.com:8000/")
        self.driver.set_window_size(1936, 1048)
        self.driver.find_element(By.LINK_TEXT, "Sign Up").click()
        self.driver.find_element(By.ID, "id_username").click()
        self.driver.find_element(By.ID, "id_username").send_keys("TestUser1")
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1)").click()
        self.driver.find_element(By.ID, "id_password1").click()
        self.driver.find_element(By.ID, "id_password1").send_keys("Complexpass123")
        time.sleep(2)
        self.driver.find_element(By.ID, "id_password2").click()
        self.driver.find_element(By.ID, "id_password2").send_keys("Complexpass123")
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "button").click()
        time.sleep(2)

    def test_login(self):
        self.driver.get("http://ec2-18-221-6-28.us-east-2.compute.amazonaws.com:8000/")
        self.driver.set_window_size(1936, 1048)
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "id_username").click()
        self.driver.find_element(By.ID, "id_username").send_keys("TestUser1")
        self.driver.find_element(By.ID, "id_password").click()
        self.driver.find_element(By.ID, "id_password").send_keys("Complexpass123")
        self.driver.find_element(By.CSS_SELECTOR, "button").click()
        time.sleep(2)        
        
    def test_viewProfile(self):
        self.driver.get("http://ec2-18-221-6-28.us-east-2.compute.amazonaws.com:8000/")
        self.driver.set_window_size(1936, 1048)
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "id_username").click()
        self.driver.find_element(By.ID, "id_username").send_keys("TestUser1")
        self.driver.find_element(By.ID, "id_password").click()
        self.driver.find_element(By.ID, "id_password").send_keys("Complexpass123")
        self.driver.find_element(By.CSS_SELECTOR, "button").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "My Profile").click()
        time.sleep(2)
        
    def test_searchListing(self):
        self.driver.get("http://ec2-18-221-6-28.us-east-2.compute.amazonaws.com:8000/")
        self.driver.find_element(By.LINK_TEXT, "Search Listings").click()
        time.sleep(1)
        self.driver.find_element(By.CSS_SELECTOR, "button").click()
        time.sleep(1)

    def test_browseListings(self):
        self.driver.get("http://ec2-18-221-6-28.us-east-2.compute.amazonaws.com:8000/")
        self.driver.set_window_size(1936, 1048)
        self.driver.find_element(By.LINK_TEXT, "Browse Listings").click()
        time.sleep(3)

    def test_viewListingDetails(self):
        self.driver.get("http://ec2-18-221-6-28.us-east-2.compute.amazonaws.com:8000/")
        self.driver.find_element(By.LINK_TEXT, "Browse Listings").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "View Details").click()
        time.sleep(3)
        
    def test_review(self):
        self.driver.get("http://ec2-18-221-6-28.us-east-2.compute.amazonaws.com:8000/")
        self.driver.set_window_size(1936, 1048)
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "id_username").click()
        self.driver.find_element(By.ID, "id_username").send_keys("TestUser1")
        self.driver.find_element(By.ID, "id_password").click()
        self.driver.find_element(By.ID, "id_password").send_keys("Complexpass123")
        self.driver.find_element(By.CSS_SELECTOR, "button").click()
        time.sleep(1)
        
        self.driver.find_element(By.LINK_TEXT, "Browse Listings").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "View Details").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "Add Review").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "id_rating").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "id_rating").send_keys("5")
        time.sleep(1)
        self.driver.find_element(By.ID, "id_comment").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "id_comment").send_keys("Amazing Product!")
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "button").click()
        time.sleep(4)
        
    def test_contactSeller(self):
        self.driver.get("http://ec2-18-221-6-28.us-east-2.compute.amazonaws.com:8000/")
        self.driver.set_window_size(1936, 1048)
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "id_username").click()
        self.driver.find_element(By.ID, "id_username").send_keys("TestUser1")
        self.driver.find_element(By.ID, "id_password").click()
        self.driver.find_element(By.ID, "id_password").send_keys("Complexpass123")
        self.driver.find_element(By.CSS_SELECTOR, "button").click()
        time.sleep(1)
        
        self.driver.get("http://ec2-18-221-6-28.us-east-2.compute.amazonaws.com:8000/")
        self.driver.find_element(By.LINK_TEXT, "Browse Listings").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "View Details").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "Contact Seller").click()
        time.sleep(2)
        self.driver.find_element(By.NAME, "message_text").click()
        time.sleep(2)
        self.driver.find_element(By.NAME, "message_text").send_keys("Still for sale?")
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "button").click()
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "Back to Inbox").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "html").click()
        time.sleep(3)
        
    def test_logout(self):
        self.driver.get("http://ec2-18-221-6-28.us-east-2.compute.amazonaws.com:8000/")
        self.driver.set_window_size(1936, 1048)
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "id_username").click()
        self.driver.find_element(By.ID, "id_username").send_keys("TestUser1")
        self.driver.find_element(By.ID, "id_password").click()
        self.driver.find_element(By.ID, "id_password").send_keys("Complexpass123")
        self.driver.find_element(By.CSS_SELECTOR, "button").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "My Profile").click()
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "Logout").click()
        time.sleep(3)
