# Generated by Django 5.2.7 on 2025-11-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='product_type',
            field=models.CharField(default='CPU', editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
