# Generated by Django 5.2.7 on 2025-11-10 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_product_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'new'), ('refurb', 'refurbished'), ('used', 'used'), ('for_parts', 'for parts')], max_length=10, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_text',
            field=models.TextField(verbose_name='Listing Text'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Upload Time'),
        ),
    ]
