# Generated by Django 5.2.7 on 2025-11-27 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_review_product_review_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
