# Generated by Django 5.2.7 on 2025-11-11 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_condition_alter_listing_listing_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-upload_time']},
        ),
        migrations.AddField(
            model_name='listing',
            name='local_pickup_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='location_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='location_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='shipping_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'Brand New'), ('like_new', 'Like New'), ('refurb', 'refurbished'), ('used', 'used'), ('for_parts', 'for parts')], max_length=10, verbose_name='Condition'),
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['order', '-is_primary'],
            },
        ),
    ]
