# Generated by Django 5.2.7 on 2025-11-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_review_uploaded_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
