# Generated by Django 5.2.7 on 2025-11-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_options_listing_local_pickup_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='product_name',
            field=models.CharField(default='Unknown Product', max_length=200),
            preserve_default=False,
        ),
    ]
