# Generated by Django 5.2.7 on 2025-11-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='product_name',
            field=models.CharField(default='Unknown Product', max_length=200, verbose_name='Product Name'),
        ),
    ]
