# Generated by Django 5.2.7 on 2025-11-11 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_product_name'),
        ('products', '0005_alter_cpu_cache_l2_alter_cpu_cache_l3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
