# Generated by Django 5.2.7 on 2025-11-12 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_product'),
        ('products', '0005_alter_cpu_cache_l2_alter_cpu_cache_l3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='listing',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
            preserve_default=False,
        ),
    ]
