# Generated by Django 5.2.7 on 2025-11-13 00:44

import django.db.models.deletion
import django.utils.timezone
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300, verbose_name='Product Name')),
                ('manufacturer', products.models.OptionalCharField(blank=True, max_length=150, null=True, verbose_name='Manufacturer')),
                ('part_numbers', models.JSONField(default=list, verbose_name='Part Numbers')),
                ('series', products.models.OptionalCharField(blank=True, max_length=150, null=True, verbose_name='Series')),
                ('variant', products.models.OptionalCharField(blank=True, max_length=150, null=True, verbose_name='Variant')),
                ('release_year', products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Release Year')),
                ('amazon_sku', products.models.OptionalCharField(blank=True, max_length=100, null=True)),
                ('newegg_sku', products.models.OptionalCharField(blank=True, max_length=100, null=True)),
                ('bestbuy_sku', products.models.OptionalCharField(blank=True, max_length=100, null=True)),
                ('walmart_sku', products.models.OptionalCharField(blank=True, max_length=100, null=True)),
                ('adorama_sku', products.models.OptionalCharField(blank=True, max_length=100, null=True)),
                ('manufacturer_url', products.models.OptionalCharField(blank=True, max_length=600, null=True)),
                ('opendb_id', models.UUIDField(unique=True)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('microarchitecture', products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Microarchitecture')),
                ('core_family', products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Core Family')),
                ('socket', products.models.OptionalCharField(blank=True, max_length=50, null=True, verbose_name='Socket')),
                ('cores_tot', products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Total Core Count')),
                ('cores_perf', products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Performance Core Count')),
                ('cores_eff', products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Efficiency Core Count')),
                ('threads', products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Thread Count')),
                ('clocks_perf_base', products.models.OptionalFloatField(blank=True, null=True, verbose_name='Performance Core Clock')),
                ('clocks_perf_boost', products.models.OptionalFloatField(blank=True, null=True, verbose_name='Performance Core Boost Clock')),
                ('clocks_eff_base', products.models.OptionalFloatField(blank=True, null=True)),
                ('clocks_eff_boost', products.models.OptionalFloatField(blank=True, null=True)),
                ('cache_l1', products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='L1 Cache')),
                ('cache_l2', products.models.OptionalFloatField(blank=True, null=True, verbose_name='L2 Cache')),
                ('cache_l3', products.models.OptionalFloatField(blank=True, null=True, verbose_name='L3 Cache')),
                ('tdp', products.models.OptionalPosIntField(blank=True, null=True, verbose_name='TDP')),
                ('intgraph_model', products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Integrated Graphics')),
                ('intgraph_base_clock', products.models.OptionalFloatField(blank=True, null=True)),
                ('intgraph_boost_clock', products.models.OptionalFloatField(blank=True, null=True)),
                ('intgraph_shader_count', products.models.OptionalFloatField(blank=True, null=True)),
                ('ecc_support', products.models.OptionalBoolField(blank=True, null=True, verbose_name='ECC Support')),
                ('includes_cooler', products.models.OptionalBoolField(blank=True, null=True, verbose_name='Includes Cooler')),
                ('packaging', products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Packaging')),
                ('lithography', products.models.OptionalCharField(blank=True, max_length=50, null=True, verbose_name='Lithography')),
                ('simul_multithread', products.models.OptionalBoolField(blank=True, null=True, verbose_name='Simultaneous Multithreading')),
                ('mem_max_support', products.models.OptionalFloatField(blank=True, null=True)),
                ('mem_types', models.JSONField(default=list)),
                ('mem_channels', products.models.OptionalPosIntField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPUs',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'GPU',
                'verbose_name_plural': 'GPUs (Not implemented)',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'Motherboard',
                'verbose_name_plural': 'Motherboards (Not implemented)',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='PCCase',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'PC Case',
                'verbose_name_plural': 'PC Cases (Not implemented)',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'Power Supply',
                'verbose_name_plural': 'Power Supplies (Not implemented)',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'RAM',
                'verbose_name_plural': 'RAM (Not implemented)',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Storage (Not implemented)',
            },
            bases=('products.product',),
        ),
    ]
