# Generated by Django 5.2.7 on 2025-10-31 05:50

import django.db.models.deletion
import django.utils.timezone
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('manufacturer', products.models.OptionalCharField(blank=True, max_length=150, null=True)),
                ('part_numbers', models.JSONField(default=list)),
                ('series', products.models.OptionalCharField(blank=True, max_length=150, null=True)),
                ('variant', products.models.OptionalCharField(blank=True, max_length=150, null=True)),
                ('release_year', products.models.OptionalPosIntField(blank=True, null=True)),
                ('amazon_sku', products.models.OptionalCharField(blank=True, max_length=100, null=True)),
                ('newegg_sku', products.models.OptionalCharField(blank=True, max_length=100, null=True)),
                ('bestbuy_sku', products.models.OptionalCharField(blank=True, max_length=100, null=True)),
                ('walmart_sku', products.models.OptionalCharField(blank=True, max_length=100, null=True)),
                ('adorama_sku', products.models.OptionalCharField(blank=True, max_length=100, null=True)),
                ('manufacturer_url', products.models.OptionalCharField(blank=True, max_length=600, null=True)),
                ('opendb_id', models.UUIDField(unique=True)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('microarchitecture', products.models.OptionalCharField(blank=True, max_length=100, null=True)),
                ('core_family', products.models.OptionalCharField(blank=True, max_length=100, null=True)),
                ('socket', products.models.OptionalCharField(blank=True, max_length=50, null=True)),
                ('cores_tot', products.models.OptionalPosIntField(blank=True, null=True)),
                ('cores_perf', products.models.OptionalPosIntField(blank=True, null=True)),
                ('cores_eff', products.models.OptionalPosIntField(blank=True, null=True)),
                ('threads', products.models.OptionalPosIntField(blank=True, null=True)),
                ('clocks_perf_base', products.models.OptionalPosIntField(blank=True, null=True)),
                ('clocks_perf_boost', products.models.OptionalPosIntField(blank=True, null=True)),
                ('clocks_eff_base', products.models.OptionalPosIntField(blank=True, null=True)),
                ('cache_l1', products.models.OptionalCharField(blank=True, max_length=100, null=True)),
                ('cache_l2', products.models.OptionalPosIntField(blank=True, null=True)),
                ('cache_l3', products.models.OptionalPosIntField(blank=True, null=True)),
                ('tdp', products.models.OptionalPosIntField(blank=True, null=True)),
                ('intgraph_model', products.models.OptionalCharField(blank=True, max_length=100, null=True)),
                ('intgraph_base_clock', products.models.OptionalPosIntField(blank=True, null=True)),
                ('intgraph_boost_clock', products.models.OptionalPosIntField(blank=True, null=True)),
                ('intgraph_shader_count', products.models.OptionalPosIntField(blank=True, null=True)),
                ('ecc_support', products.models.OptionalBoolField(blank=True, null=True)),
                ('includes_cooler', products.models.OptionalBoolField(blank=True, null=True)),
                ('packaging', products.models.OptionalCharField(blank=True, max_length=100, null=True)),
                ('lithography', products.models.OptionalCharField(blank=True, max_length=50, null=True)),
                ('simul_multithread', products.models.OptionalBoolField(blank=True, null=True)),
                ('mem_max_support', products.models.OptionalPosIntField(blank=True, null=True)),
                ('mem_types', models.JSONField(default=list)),
                ('mem_channels', products.models.OptionalPosIntField(blank=True, null=True)),
            ],
            bases=('products.product',),
        ),
    ]
