# Generated by Django 5.2.7 on 2025-11-12 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'GPU',
                'verbose_name_plural': 'GPUs (Not implemented)',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'Motherboard',
                'verbose_name_plural': 'Motherboards (Not implemented)',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='PCCase',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'PC Case',
                'verbose_name_plural': 'PC Cases (Not implemented)',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'Power Supply',
                'verbose_name_plural': 'Power Supplies (Not implemented)',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'RAM',
                'verbose_name_plural': 'RAM (Not implemented)',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Storage (Not implemented)',
            },
            bases=('products.product',),
        ),
    ]
