# Generated by Django 5.2.7 on 2025-10-31 06:02

import products.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='clocks_eff_boost',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
    ]
