# Generated by Django 5.2.7 on 2025-11-27 21:37

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='case_expansion_slot_width',
            field=products.models.OptionalFloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='chipset',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Chipset'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='chipset_manufacturer',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='color',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gpu',
            name='cooling',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='core_base_clock',
            field=products.models.OptionalFloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='core_boost_clock',
            field=products.models.OptionalFloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='core_count',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='displayport_1_4a',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='displayport_2_1',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='displayport_2_1_b',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='displayport_2_1a',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='dvi_d',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='effective_memory_clock',
            field=products.models.OptionalFloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='frame_sync',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Frame Sync'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='hdmi_2_0',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='hdmi_2_1',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='hdmi_2_2',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='interface',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Interface'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='length',
            field=products.models.OptionalFloatField(blank=True, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='memory',
            field=products.models.OptionalFloatField(blank=True, null=True, verbose_name='Memory'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='memory_bus',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='memory_type',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Memory Type'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='pcie_12VHPWR',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='pcie_12V_2x6',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='pcie_6_pin',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='pcie_8_pin',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='tdp',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='TDP'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='total_slot_width',
            field=products.models.OptionalFloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='vga',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
    ]
