# Generated by Django 5.2.7 on 2025-11-07 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0002_cpu_clocks_eff_boost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='product',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
