# Generated by Django 5.2.7 on 2025-11-27 23:09

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_gpu_case_expansion_slot_width_gpu_chipset_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpu',
            options={'verbose_name': 'GPU', 'verbose_name_plural': 'GPUs'},
        ),
        migrations.AlterModelOptions(
            name='motherboard',
            options={'verbose_name': 'Motherboard', 'verbose_name_plural': 'Motherboards'},
        ),
        migrations.AddField(
            model_name='motherboard',
            name='argb_5v',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='case_fan',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='chipset',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Chipset'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='color',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='cpu_fan',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='cpu_opt',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='form_factor',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Form Factor'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='m2_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='memory_max',
            field=products.models.OptionalFloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='memory_ram_type',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='RAM Type'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='memory_slots',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='RAM Slots'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='onboard_ethernets',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='pcie_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='pump',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='rgb_12v',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='sata_3_gb_s',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='sata_6_gb_s',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='socket',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Socket'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='u2',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='usb_2_0',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='usb_3_2_gen_1',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='usb_3_2_gen_2',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='usb_3_2_gen_2x2',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='usb_4',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='usb_4_80g',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='wireless_networking',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True),
        ),
    ]
