# Generated by Django 5.2.7 on 2025-11-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_gpu_options_alter_motherboard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='color',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='m2_slots',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='onboard_ethernets',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='pcie_slots',
            field=models.JSONField(default=list, null=True),
        ),
    ]
