# Generated by Django 5.2.7 on 2025-11-09 18:29

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_cpu_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='cache_l1',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='L1 Cache'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cache_l2',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='L2 Cache'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cache_l3',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='L3 Cache'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='clocks_perf_base',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Performance Core Clock'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='clocks_perf_boost',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Performance Core Boost Clock'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='core_family',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Core Family'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cores_eff',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Efficiency Core Count'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cores_perf',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Performance Core Count'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cores_tot',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Total Core Count'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='ecc_support',
            field=products.models.OptionalBoolField(blank=True, null=True, verbose_name='ECC Support'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='includes_cooler',
            field=products.models.OptionalBoolField(blank=True, null=True, verbose_name='Includes Cooler'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='intgraph_model',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Integrated Graphics'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='lithography',
            field=products.models.OptionalCharField(blank=True, max_length=50, null=True, verbose_name='Lithography'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='microarchitecture',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Microarchitecture'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='packaging',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Packaging'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='simul_multithread',
            field=products.models.OptionalBoolField(blank=True, null=True, verbose_name='Simultaneous Multithreading'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='socket',
            field=products.models.OptionalCharField(blank=True, max_length=50, null=True, verbose_name='Socket'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='tdp',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='TDP'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='threads',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Thread Count'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=products.models.OptionalCharField(blank=True, max_length=150, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='part_numbers',
            field=models.JSONField(default=list, verbose_name='Part Numbers'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=300, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_year',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Release Year'),
        ),
        migrations.AlterField(
            model_name='product',
            name='series',
            field=products.models.OptionalCharField(blank=True, max_length=150, null=True, verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=products.models.OptionalCharField(blank=True, max_length=150, null=True, verbose_name='Variant'),
        ),
    ]
