# Generated by Django 5.2.7 on 2025-11-10 05:38

import products.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_cpu_cache_l1_alter_cpu_cache_l2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='cache_l2',
            field=products.models.OptionalDecField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='L2 Cache'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cache_l3',
            field=products.models.OptionalDecField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='L3 Cache'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='clocks_eff_base',
            field=products.models.OptionalDecField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='clocks_eff_boost',
            field=products.models.OptionalDecField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='clocks_perf_base',
            field=products.models.OptionalDecField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Performance Core Clock'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='clocks_perf_boost',
            field=products.models.OptionalDecField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Performance Core Boost Clock'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='intgraph_base_clock',
            field=products.models.OptionalDecField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='intgraph_boost_clock',
            field=products.models.OptionalDecField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='intgraph_shader_count',
            field=products.models.OptionalDecField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='mem_max_support',
            field=products.models.OptionalDecField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
