# Generated by Django 5.2.7 on 2025-12-01 03:14

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_motherboard_color_alter_motherboard_m2_slots_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pccase',
            options={'verbose_name': 'PC Case', 'verbose_name_plural': 'PC Cases'},
        ),
        migrations.AddField(
            model_name='pccase',
            name='color',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pccase',
            name='depth',
            field=products.models.OptionalFloatField(blank=True, null=True, verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='pccase',
            name='expansion_slots',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Expansion Slots'),
        ),
        migrations.AddField(
            model_name='pccase',
            name='external_3_5_bays',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pccase',
            name='external_5_25_bays',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pccase',
            name='form_factor',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Form Factor'),
        ),
        migrations.AddField(
            model_name='pccase',
            name='front_usb_ports',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pccase',
            name='has_transparent_side_panel',
            field=products.models.OptionalBoolField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pccase',
            name='height',
            field=products.models.OptionalFloatField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='pccase',
            name='internal_2_5_bays',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pccase',
            name='internal_3_5_bays',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pccase',
            name='max_cpu_cooler_height',
            field=products.models.OptionalFloatField(blank=True, null=True, verbose_name='Max CPU Cooler Height'),
        ),
        migrations.AddField(
            model_name='pccase',
            name='max_video_card_length',
            field=products.models.OptionalFloatField(blank=True, null=True, verbose_name='Max GPU Length'),
        ),
        migrations.AddField(
            model_name='pccase',
            name='power_supply',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pccase',
            name='power_supply_included',
            field=products.models.OptionalBoolField(blank=True, null=True, verbose_name='Includes PSU'),
        ),
        migrations.AddField(
            model_name='pccase',
            name='power_supply_shroud',
            field=products.models.OptionalBoolField(blank=True, null=True, verbose_name='Includes PSU Shroud'),
        ),
        migrations.AddField(
            model_name='pccase',
            name='riser_expansion_slots',
            field=products.models.OptionalPosIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pccase',
            name='side_panel',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Side Panel'),
        ),
        migrations.AddField(
            model_name='pccase',
            name='supports_rear_connecting_motherboard',
            field=products.models.OptionalBoolField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pccase',
            name='volume',
            field=products.models.OptionalFloatField(blank=True, null=True, verbose_name='Volume'),
        ),
        migrations.AddField(
            model_name='pccase',
            name='weight',
            field=products.models.OptionalFloatField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='pccase',
            name='width',
            field=products.models.OptionalFloatField(blank=True, null=True, verbose_name='Width'),
        ),
    ]
