# Generated by Django 5.2.7 on 2025-11-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_cpu_cache_l2_alter_cpu_cache_l3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'managed': True, 'verbose_name': 'CPU', 'verbose_name_plural': 'CPUs'},
        ),
        migrations.AlterModelTable(
            name='cpu',
            table='',
        ),
    ]
