# Generated by Django 5.2.7 on 2025-12-01 03:56

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_pccase_options_pccase_color_pccase_depth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psu',
            options={'verbose_name': 'Power Supply', 'verbose_name_plural': 'Power Supplies'},
        ),
        migrations.AddField(
            model_name='psu',
            name='atx_24_pin',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='ATX 24 Pin'),
        ),
        migrations.AddField(
            model_name='psu',
            name='color',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='psu',
            name='cybernetics_efficiency_rating',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='psu',
            name='cybernetics_noise_rating',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='psu',
            name='efficiency_rating',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Efficiency Rating'),
        ),
        migrations.AddField(
            model_name='psu',
            name='eps_8_pin',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='EPS 8 Pin'),
        ),
        migrations.AddField(
            model_name='psu',
            name='fanless',
            field=products.models.OptionalBoolField(blank=True, null=True, verbose_name='Fanless'),
        ),
        migrations.AddField(
            model_name='psu',
            name='floppy_4_pin',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Floppy 4 Pin'),
        ),
        migrations.AddField(
            model_name='psu',
            name='form_factor',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Form Factor'),
        ),
        migrations.AddField(
            model_name='psu',
            name='length',
            field=products.models.OptionalFloatField(blank=True, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='psu',
            name='modular',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Modular'),
        ),
        migrations.AddField(
            model_name='psu',
            name='molex_4_pin',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Molex 4 Pin'),
        ),
        migrations.AddField(
            model_name='psu',
            name='pcie_12vhpwr',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='PCIE 12VHPWR'),
        ),
        migrations.AddField(
            model_name='psu',
            name='pcie_6_plus_2_pin',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='PCIE 6+2'),
        ),
        migrations.AddField(
            model_name='psu',
            name='sata',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='SATA'),
        ),
        migrations.AddField(
            model_name='psu',
            name='wattage',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Wattage'),
        ),
    ]
