# Generated by Django 5.2.7 on 2025-12-01 04:26

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_psu_options_psu_atx_24_pin_psu_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': 'RAM', 'verbose_name_plural': 'RAM'},
        ),
        migrations.AddField(
            model_name='ram',
            name='capacity',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Total Capcity'),
        ),
        migrations.AddField(
            model_name='ram',
            name='cas_latency',
            field=products.models.OptionalFloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='color',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ram',
            name='ecc',
            field=products.models.OptionalCharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='form_factor',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True, verbose_name='Form Factor'),
        ),
        migrations.AddField(
            model_name='ram',
            name='heat_spreader',
            field=products.models.OptionalBoolField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='height',
            field=products.models.OptionalFloatField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='ram',
            name='module_capacity_gb',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Capacity Per Module'),
        ),
        migrations.AddField(
            model_name='ram',
            name='module_quantity',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Module Quantity'),
        ),
        migrations.AddField(
            model_name='ram',
            name='ram_type',
            field=products.models.OptionalCharField(blank=True, max_length=50, null=True, verbose_name='Ram Type'),
        ),
        migrations.AddField(
            model_name='ram',
            name='registered',
            field=products.models.OptionalCharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='rgb',
            field=products.models.OptionalBoolField(blank=True, null=True, verbose_name='Has RGB'),
        ),
        migrations.AddField(
            model_name='ram',
            name='speed',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Speed'),
        ),
        migrations.AddField(
            model_name='ram',
            name='timings',
            field=products.models.OptionalCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='voltage',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Voltage'),
        ),
    ]
