# Generated by Django 5.2.7 on 2025-12-01 04:55

import products.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_ram_options_ram_capacity_ram_cas_latency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Storage', 'verbose_name_plural': 'Storage'},
        ),
        migrations.AddField(
            model_name='storage',
            name='cache',
            field=products.models.OptionalFloatField(blank=True, null=True, verbose_name='Cache'),
        ),
        migrations.AddField(
            model_name='storage',
            name='capacity',
            field=products.models.OptionalPosIntField(blank=True, null=True, verbose_name='Capacity'),
        ),
        migrations.AddField(
            model_name='storage',
            name='form_factor',
            field=products.models.OptionalCharField(blank=True, max_length=25, null=True, verbose_name='Form Factor'),
        ),
        migrations.AddField(
            model_name='storage',
            name='interface',
            field=products.models.OptionalCharField(blank=True, max_length=50, null=True, verbose_name='Interface'),
        ),
        migrations.AddField(
            model_name='storage',
            name='nvme',
            field=products.models.OptionalBoolField(blank=True, null=True, verbose_name='Uses NVME'),
        ),
        migrations.AddField(
            model_name='storage',
            name='type',
            field=products.models.OptionalCharField(blank=True, max_length=25, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='voltage',
            field=products.models.OptionalFloatField(blank=True, null=True, verbose_name='Voltage'),
        ),
    ]
